apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hib7ktmn5-nodejs
  janus-idp.io/tekton: hib7ktmn5-nodejs
  backstage.io/kubernetes-id: hib7ktmn5-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hib7ktmn5-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
